baseURL = ""
title = "Apache ShenYu"

languageCode = "zh-CN"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
enableGitInfo = true

disableKinds = ["taxonomyTerm"]

Paginate = 10
googleAnalytics = "UA-187960192-2"
[markup.goldmark.renderer]
unsafe = true
[params]
	github = "https://github.com/apache/incubator-shenyu-website"
  description = "The girl on the prairie"

# 首页订阅
[params.homeSubscription]
	enable = false

# algolia
[outputFormats.Algolia]
	baseName = "algolia"
	isPlainText = true
	mediaType = "application/json"
	notAlternative = true

[params.algolia]
	vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
	params = ["categories", "tags", "series"]

[outputs]
 home = ["HTML", "RSS", "Algolia"]

[languages]
	[languages.en]
        contentDir = "content/en"
        languageName = "English"
        weight = 10
	[languages.zh]
		contentDir = "content/zh"
		languageName = "中文"
		weight = 20

	[[languages.zh.menu.main]]
		identifier = "download"
		name = "下载"
		url = "/zh/projects/shenyu/download/"
		weight = 1
	[[languages.zh.menu.main]]
		identifier = "document"
		name = "文档"
		url = "/zh/projects/shenyu/overview/"
		weight = 2
	[[languages.zh.menu.main]]
		identifier = "community"
		name = "社区"
		url = "/zh/community/subscribe-email/"
		weight = 3
	[[languages.zh.menu.main]]
		identifier = "news"
		name = "新闻"
		url = "/zh/news/"
		weight = 4
	# [[languages.zh.menu.main]]
		# identifier = "blog"
		# name = "博客"
		# url = "/zh/blog/"
		# weight = 5

[menu]
	[[menu.main]]
		identifier = "download"
		name = "Download"
		url = "/projects/shenyu/download/"
		weight = 1
	[[menu.main]]
		identifier = "document"
		name = "Documentation"
		url = "/projects/shenyu/overview/"
		weight = 2
	[[menu.main]]
		identifier = "community"
		name = "Community"
		url = "/community/subscribe-email/"
		weight = 3
	[[menu.main]]
		identifier = "news"
		name = "News"
		url = "/news/"
		weight = 4
	# [[menu.main]]
		# identifier = "blog"
		# name = "Blog"
		# url = "/blog/"
		# weight = 5

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
