name: Build Docs PDF
on: [workflow_dispatch]

jobs:
  build:
    name: Publish PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python Env
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Generate PDF
        run: |
          bash .github/scripts/generate-pdf.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: asf-site
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_dir: ./public/pdf
          destination_dir: pdf
          commit_message: 'Updated pdf'
          keep_files: true
